- name: Pull and run docker image
  hosts: all
  tasks:
    - name: Cleanup
      shell: docker ps -aq --filter name="calculator" | xargs docker stop | xargs docker rm
    - name: Pull docker image
      shell: docker pull {{ docker_image }}
    - name: Run docker image
      shell: docker run -i -t  --name calculator -d {{ docker_image }}